In [4]:
import pandas as pd

## LENDO O CSV

In [5]:
df = pd.read_csv('Competências_Avaliação de Terceiros.csv', sep=',')

In [6]:
df.head()

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Desenvolvimento Contínuo_Devolutiva,Desenvolvimento Contínuo_Diálogo,...,Adaptação e Inovação_Revê,Adaptação e Inovação_Planejamento,Capacidade de Execução_Constância,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,2.0,2.0,...,3.0,2.0,3.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,3.0,...,4.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0

Verificando se existe duplicatas

In [7]:
df.duplicated().sum()

np.int64(0)

## Desenvolvimento Contínuo

In [8]:
# Criando uma copia para o df.
df_copia = df
df_copia

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Desenvolvimento Contínuo_Devolutiva,Desenvolvimento Contínuo_Diálogo,...,Adaptação e Inovação_Revê,Adaptação e Inovação_Planejamento,Capacidade de Execução_Constância,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,2.0,2.0,...,3.0,2.0,3.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,3.0,...,4.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,3.0,3.0,...,3.0,3.0,4.0,2.0,2.0,3.0,2.0,3.0,4.0,2.0
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,3.0,3.0,...,3.0,3.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,2.0,...,2.0,3.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,NaN
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,4.0,3.0,...,2.0,2.0,2.0,2.0,2.0,NaN,3.0,2.0,2.0,2.0
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,4.0,2.0,...,3.0,2.0,3.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0

In [9]:
# Primeiro, criamos uma lista com o nome exato das colunas "micro"
cols_desenv_continuo = [
    'Desenvolvimento Contínuo_Devolutiva', 
    'Desenvolvimento Contínuo_Diálogo', 
    'Desenvolvimento Contínuo_Compartilha', 
    'Desenvolvimento Contínuo_Referência'
]

In [10]:
# Criamos a nova coluna "macro".
# O comando .mean(axis=1) tira a média da linha e já dividimos por 4.
df_copia['Desenvolvimento Contínuo'] = df_copia[cols_desenv_continuo].mean(axis=1) / 4

In [11]:
# removemos as colunas "micro" antigas para não poluir a base
df_copia = df_copia.drop(columns=cols_desenv_continuo)

In [12]:
# Atribuo o df de copia ao original
df = df_copia

In [13]:
# Deleto o "df_copia"
del df_copia

In [14]:
df.head()

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Visão Estratégica_Resultados,Visão Estratégica_Ajustar,...,Adaptação e Inovação_Planejamento,Capacidade de Execução_Constância,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0000
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,3.0,2.0,...,2.0,3.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,0.5625
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.6875
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0000

## Visão Estratégica

In [15]:
# Criando uma copia para o df.
df_copia = df
df_copia

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Visão Estratégica_Resultados,Visão Estratégica_Ajustar,...,Adaptação e Inovação_Planejamento,Capacidade de Execução_Constância,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,3.0,2.0,...,2.0,3.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,0.562500
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.687500
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,3.0,2.0,...,3.0,4.0,2.0,2.0,3.0,2.0,3.0,4.0,2.0,0.687500
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,2.0,...,3.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,0.562500
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,2.0,...,3.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,NaN,0.583333
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,2.0,3.0,...,2.0,2.0,2.0,2.0,NaN,3.0,2.0,2.0,2.0,0.875000
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,2.0,2.0,...,2.0,3.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,0.625000

In [16]:
# Primeiro, criamos uma lista com o nome exato das colunas "micro"
cols_visao_estrategica = [
    'Visão Estratégica_Resultados', 
    'Visão Estratégica_Ajustar', 
    'Visão Estratégica_Coerência', 
    'Visão Estratégica_Conectar'
]

In [17]:
# Criamos a nova coluna "macro".
# O comando .mean(axis=1) tira a média da linha e já dividimos por 4.
df_copia['Visão Estratégica'] = df_copia[cols_visao_estrategica].mean(axis=1) / 4

In [18]:
# Removo as colunas "micro" antigas para não poluir a base
df_copia = df_copia.drop(columns=cols_visao_estrategica)

In [19]:
# Atribuo o df de copia ao original
df = df_copia
df

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Colaboração e Parceria_Abertura,Colaboração e Parceria_Engaja,...,Capacidade de Execução_Constância,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo,Visão Estratégica
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,3.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,2.0,2.0,...,3.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,0.562500,0.6250
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,2.0,2.0,...,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.687500,1.0000
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,2.0,3.0,...,4.0,2.0,2.0,3.0,2.0,3.0,4.0,2.0,0.687500,0.6875
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,3.0,4.0,...,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,0.562500,0.6250
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,3.0,...,2.0,2.0,2.0,2.0,1.0,1.0,3.0,NaN,0.583333,0.5625
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,4.0,3.0,...,2.0,2.0,2.0,NaN,3.0,2.0,2.0,2.0,0.875000,0.5625
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,4.0,4.0,...,3.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,0.625000,0.5000

In [20]:
# Deleto o "df_copia"
del df_copia

## Colaboração e Parceria

In [21]:
# Criando uma copia para o df.
df_copia = df
df_copia

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Colaboração e Parceria_Abertura,Colaboração e Parceria_Engaja,...,Capacidade de Execução_Constância,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo,Visão Estratégica
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,3.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,2.0,2.0,...,3.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,0.562500,0.6250
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,2.0,2.0,...,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.687500,1.0000
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,2.0,3.0,...,4.0,2.0,2.0,3.0,2.0,3.0,4.0,2.0,0.687500,0.6875
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,3.0,4.0,...,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,0.562500,0.6250
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,3.0,...,2.0,2.0,2.0,2.0,1.0,1.0,3.0,NaN,0.583333,0.5625
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,4.0,3.0,...,2.0,2.0,2.0,NaN,3.0,2.0,2.0,2.0,0.875000,0.5625
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,4.0,4.0,...,3.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,0.625000,0.5000

In [22]:
# Primeiro, criamos uma lista com o nome exato das colunas "micro"
cols_colabo_parceria = [
    'Colaboração e Parceria_Abertura', 
    'Colaboração e Parceria_Engaja', 
    'Colaboração e Parceria_Ajuda', 
    'Colaboração e Parceria_Parceria'
]

In [23]:
# Criamos a nova coluna "macro".
# O comando .mean(axis=1) tira a média da linha e já dividimos por 4.
df_copia['Colaboração e Parceria'] = df_copia[cols_colabo_parceria].mean(axis=1) / 4

In [24]:
# Removo as colunas "micro" antigas para não poluir a base
df_copia = df_copia.drop(columns=cols_colabo_parceria)

In [25]:
# Atribuo o df de copia ao original
df = df_copia
df

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Adaptação e Inovação_Inovação,Adaptação e Inovação_Metodologia,...,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,0.812500
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,1.0,2.0,...,1.0,2.0,2.0,3.0,2.0,2.0,2.0,0.562500,0.6250,0.500000
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.687500,1.0000,0.625000
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,3.0,2.0,...,2.0,2.0,3.0,2.0,3.0,4.0,2.0,0.687500,0.6875,0.750000
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,3.0,3.0,...,4.0,3.0,3.0,3.0,3.0,3.0,3.0,0.562500,0.6250,0.812500
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,2.0,...,2.0,2.0,2.0,1.0,1.0,3.0,NaN,0.583333,0.5625,0.666667
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,2.0,2.0,...,2.0,2.0,NaN,3.0,2.0,2.0,2.0,0.875000,0.5625,0.833333
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,4.0,4.0,...,2.0,3.0,3.0,1.0,3.0,3.0,2.0,0.625000,0.5000,0.875000

In [26]:
# Deleto o "df_copia"
del df_copia

## Adaptação e Inovação

In [27]:
# Criando uma copia para o df.
df_copia = df
df_copia

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Adaptação e Inovação_Inovação,Adaptação e Inovação_Metodologia,...,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,0.812500
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,1.0,2.0,...,1.0,2.0,2.0,3.0,2.0,2.0,2.0,0.562500,0.6250,0.500000
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.687500,1.0000,0.625000
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,3.0,2.0,...,2.0,2.0,3.0,2.0,3.0,4.0,2.0,0.687500,0.6875,0.750000
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,3.0,3.0,...,4.0,3.0,3.0,3.0,3.0,3.0,3.0,0.562500,0.6250,0.812500
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,2.0,...,2.0,2.0,2.0,1.0,1.0,3.0,NaN,0.583333,0.5625,0.666667
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,2.0,2.0,...,2.0,2.0,NaN,3.0,2.0,2.0,2.0,0.875000,0.5625,0.833333
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,4.0,4.0,...,2.0,3.0,3.0,1.0,3.0,3.0,2.0,0.625000,0.5000,0.875000

In [28]:
# Crio uma lista com o nome exato das colunas "micro"
cols_adapt_inova = [
    'Adaptação e Inovação_Inovação', 
    'Adaptação e Inovação_Metodologia', 
    'Adaptação e Inovação_Revê', 
    'Adaptação e Inovação_Planejamento'
]

In [29]:
# Crio uma nova coluna "macro".
# O comando .mean(axis=1) tira a média da linha e já dividimos por 4.
df_copia['Adaptação e Inovação'] = df_copia[cols_adapt_inova].mean(axis=1) / 4

In [30]:
# Removo as colunas "micro" antigas para não poluir a base
df_copia = df_copia.drop(columns=cols_adapt_inova)

In [31]:
# Atribuo o df de copia ao original
df = df_copia
df

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Capacidade de Execução_Constância,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,0.812500,1.0000
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,3.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,0.562500,0.6250,0.500000,0.5000
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000,1.0000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.687500,1.0000,0.625000,1.0000
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,4.0,2.0,2.0,3.0,2.0,3.0,4.0,2.0,0.687500,0.6875,0.750000,0.6875
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,0.562500,0.6250,0.812500,0.7500
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,2.0,2.0,2.0,1.0,1.0,3.0,NaN,0.583333,0.5625,0.666667,0.5625
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,2.0,2.0,2.0,NaN,3.0,2.0,2.0,2.0,0.875000,0.5625,0.833333,0.5000
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,3.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,0.625000,0.5000,0.875000,0.8125

In [32]:
# Deleto o "df_copia"
del df_copia

## Capacidade de Execução

In [33]:
# Criando uma copia para o df.
df_copia = df.copy()
df_copia

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Capacidade de Execução_Constância,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,0.812500,1.0000
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,3.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,0.562500,0.6250,0.500000,0.5000
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000,1.0000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.687500,1.0000,0.625000,1.0000
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,4.0,2.0,2.0,3.0,2.0,3.0,4.0,2.0,0.687500,0.6875,0.750000,0.6875
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,0.562500,0.6250,0.812500,0.7500
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,2.0,2.0,2.0,1.0,1.0,3.0,NaN,0.583333,0.5625,0.666667,0.5625
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,2.0,2.0,2.0,NaN,3.0,2.0,2.0,2.0,0.875000,0.5625,0.833333,0.5000
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,3.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,0.625000,0.5000,0.875000,0.8125

In [34]:
# Crio uma lista com o nome exato das colunas "micro"
cols_capaci_execucao = [
    'Capacidade de Execução_Constância', 
    'Capacidade de Execução_Concreta', 
    'Capacidade de Execução_Padrões', 
    'Capacidade de Execução_Planos'
]

In [35]:
# Crio uma nova coluna "macro".
# O comando .mean(axis=1) tira a média da linha e já dividimos por 4.
df_copia['Capacidade de Execução'] = df_copia[cols_capaci_execucao].mean(axis=1) / 4

In [36]:
# Removo as colunas "micro" antigas para não poluir a base
df_copia = df_copia.drop(columns=cols_capaci_execucao)

In [37]:
# Atribuo o df de copia ao original
df = df_copia
df.head(1)

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação,Capacidade de Execução
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,4.0,4.0,1.0,1.0,0.8125,1.0,1.0

In [38]:
# Deleto o "df_copia"
del df_copia

## Comunicação Empática

In [39]:
# Criando uma copia para o df.
df_copia = df.copy()
df_copia

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação,Capacidade de Execução
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,4.0,4.0,1.000000,1.0000,0.812500,1.0000,1.0000
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,3.0,2.0,2.0,2.0,0.562500,0.6250,0.500000,0.5000,0.5000
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000,1.0000,1.0000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,4.0,4.0,0.687500,1.0000,0.625000,1.0000,0.9375
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000,1.0000,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,2.0,3.0,4.0,2.0,0.687500,0.6875,0.750000,0.6875,0.6875
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,3.0,3.0,3.0,3.0,0.562500,0.6250,0.812500,0.7500,0.8125
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,1.0,1.0,3.0,NaN,0.583333,0.5625,0.666667,0.5625,0.5000
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,3.0,2.0,2.0,2.0,0.875000,0.5625,0.833333,0.5000,0.5000
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,1.0,3.0,3.0,2.0,0.625000,0.5000,0.875000,0.8125,0.6875

In [40]:
# Crio uma lista com o nome exato das colunas "micro"
cols_comunica_empati= [
    'Comunicação Empática_Expectativa', 
    'Comunicação Empática_Conflitos', 
    'Comunicação Empática_Sensibilidade', 
    'Comunicação Empática_Diálogo'
]

In [41]:
# Crio uma nova coluna "macro".
# O comando .mean(axis=1) tira a média da linha e já dividimos por 4.
df_copia['Comunicação Empática'] = df_copia[cols_comunica_empati].mean(axis=1) / 4

In [42]:
# Removo as colunas "micro" antigas para não poluir a base
df_copia = df_copia.drop(columns=cols_comunica_empati)

In [43]:
# Atribuo o df de copia ao original
df = df_copia
df.head(1)

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação,Capacidade de Execução,Comunicação Empática
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,1.0,1.0,0.8125,1.0,1.0,1.0

In [44]:
# Deleto o "df_copia"
del df_copia

## Arredondando as casas decimais das competencias

In [45]:
df_copia = df.copy()
df_copia

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação,Capacidade de Execução,Comunicação Empática
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,1.000000,1.0000,0.812500,1.0000,1.0000,1.000000
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,0.562500,0.6250,0.500000,0.5000,0.5000,0.562500
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,1.000000,1.0000,1.000000,1.0000,1.0000,1.000000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,0.687500,1.0000,0.625000,1.0000,0.9375,1.000000
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,1.000000,1.0000,1.000000,1.0000,1.0000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,0.687500,0.6875,0.750000,0.6875,0.6875,0.687500
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,0.562500,0.6250,0.812500,0.7500,0.8125,0.750000
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,0.583333,0.5625,0.666667,0.5625,0.5000,0.416667
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,0.875000,0.5625,0.833333,0.5000,0.5000,0.562500
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,0.625000,0.5000,0.875000,0.8125,0.6875,0.562500

In [46]:
# Agrupando as colunas das competências em uma lista para facilitar
colunas_competencias = [
    'Desenvolvimento Contínuo', 
    'Visão Estratégica', 
    'Colaboração e Parceria', 
    'Adaptação e Inovação', 
    'Capacidade de Execução', 
    'Comunicação Empática'
]

# Aplicando o arredondamento de 2 casas decimais substituindo os valores antigos
df_copia[colunas_competencias] = df_copia[colunas_competencias].round(2)

In [ ]:
# Atribuindo "df_copia" a "df"
df = df_copia

In [50]:
# Deleto o "df_copia"
del df_copia

## SALVAR O CSV COM AS MUDANÇAS

In [52]:
df.to_csv("Arquivo_Tratado_Avaliação_Terceiros", index=False)