In [1]:
import pandas as pd

## Lendo o CSV

In [3]:
df = pd.read_csv('Competências_Autoavaliação.csv', sep=',')

In [4]:
df.head()

,Registro_Ensina,Adaptação e Inovação,Capacidade de Execução,Colaboração e Parceria,Comunicação Empática e Mobilizadora,Desenvolvimento Contínuo,Visão Estratégica e Resolução de Problemas
0,240.216,2%,37%,15%,85%,77%,6%
1,240.003,85%,89%,77%,55%,68%,72%
2,240.062,23%,69%,71%,29%,34%,66%
3,240.202,24%,80%,54%,58%,81%,27%
4,240.093,100%,98%,100%,100%,97%,94%

## Adaptação e Inovação

In [ ]:
# Criando uma cópia
df_copia = df.copy()

In [6]:
# Tiramos o símbolo de '%' usando manipulação de string (.str.replace)
# Convertemos o texto que sobrou para número decimal (.astype(float))
# Dividimos por 100 para ficar na escala de 0 a 1 (ex: 85 vira 0.85)

df_copia['Adaptação e Inovação'] = df_copia['Adaptação e Inovação'].str.replace('%', '').astype(float) / 100

In [7]:
df_copia.head()

,Registro_Ensina,Adaptação e Inovação,Capacidade de Execução,Colaboração e Parceria,Comunicação Empática e Mobilizadora,Desenvolvimento Contínuo,Visão Estratégica e Resolução de Problemas
0,240.216,0.02,37%,15%,85%,77%,6%
1,240.003,0.85,89%,77%,55%,68%,72%
2,240.062,0.23,69%,71%,29%,34%,66%
3,240.202,0.24,80%,54%,58%,81%,27%
4,240.093,1.00,98%,100%,100%,97%,94%

In [8]:
# Atribuo o df de copia ao original
df = df_copia

In [9]:
# Deleto o "df_copia"
del df_copia

In [10]:
df

,Registro_Ensina,Adaptação e Inovação,Capacidade de Execução,Colaboração e Parceria,Comunicação Empática e Mobilizadora,Desenvolvimento Contínuo,Visão Estratégica e Resolução de Problemas
0,240.216,0.02,37%,15%,85%,77%,6%
1,240.003,0.85,89%,77%,55%,68%,72%
2,240.062,0.23,69%,71%,29%,34%,66%
3,240.202,0.24,80%,54%,58%,81%,27%
4,240.093,1.00,98%,100%,100%,97%,94%
...,...,...,...,...,...,...,...
171,240.038,0.99,65%,92%,47%,93%,92%
172,250.055,0.90,13%,53%,53%,36%,2%
173,240.102,0.93,65%,98%,98%,90%,92%
174,240.132,0.05,9%,9%,3%,9%,20%
175,250.152,0.76,46%,96%,47%,88%,92%

## Capacidade de Execução

In [11]:
# Criando uma cópia
df_copia = df.copy()

In [12]:
# Tiramos o símbolo de '%' usando manipulação de string (.str.replace)
# Convertemos o texto que sobrou para número decimal (.astype(float))
# Dividimos por 100 para ficar na escala de 0 a 1 (ex: 85 vira 0.85)

df_copia['Capacidade de Execução'] = df_copia['Capacidade de Execução'].str.replace('%', '').astype(float) / 100

In [13]:
df_copia.head()

,Registro_Ensina,Adaptação e Inovação,Capacidade de Execução,Colaboração e Parceria,Comunicação Empática e Mobilizadora,Desenvolvimento Contínuo,Visão Estratégica e Resolução de Problemas
0,240.216,0.02,0.37,15%,85%,77%,6%
1,240.003,0.85,0.89,77%,55%,68%,72%
2,240.062,0.23,0.69,71%,29%,34%,66%
3,240.202,0.24,0.80,54%,58%,81%,27%
4,240.093,1.00,0.98,100%,100%,97%,94%

In [14]:
# Atribuo o df de copia ao original
df = df_copia

In [15]:
# Deleto o "df_copia"
del df_copia

In [16]:
df

,Registro_Ensina,Adaptação e Inovação,Capacidade de Execução,Colaboração e Parceria,Comunicação Empática e Mobilizadora,Desenvolvimento Contínuo,Visão Estratégica e Resolução de Problemas
0,240.216,0.02,0.37,15%,85%,77%,6%
1,240.003,0.85,0.89,77%,55%,68%,72%
2,240.062,0.23,0.69,71%,29%,34%,66%
3,240.202,0.24,0.80,54%,58%,81%,27%
4,240.093,1.00,0.98,100%,100%,97%,94%
...,...,...,...,...,...,...,...
171,240.038,0.99,0.65,92%,47%,93%,92%
172,250.055,0.90,0.13,53%,53%,36%,2%
173,240.102,0.93,0.65,98%,98%,90%,92%
174,240.132,0.05,0.09,9%,3%,9%,20%
175,250.152,0.76,0.46,96%,47%,88%,92%

## Colaboração e Parceria

In [17]:
# Criando uma cópia
df_copia = df.copy()

In [18]:
# Tiramos o símbolo de '%' usando manipulação de string (.str.replace)
# Convertemos o texto que sobrou para número decimal (.astype(float))
# Dividimos por 100 para ficar na escala de 0 a 1 (ex: 85 vira 0.85)

df_copia['Colaboração e Parceria'] = df_copia['Colaboração e Parceria'].str.replace('%', '').astype(float) / 100

In [19]:
df_copia.head()

,Registro_Ensina,Adaptação e Inovação,Capacidade de Execução,Colaboração e Parceria,Comunicação Empática e Mobilizadora,Desenvolvimento Contínuo,Visão Estratégica e Resolução de Problemas
0,240.216,0.02,0.37,0.15,85%,77%,6%
1,240.003,0.85,0.89,0.77,55%,68%,72%
2,240.062,0.23,0.69,0.71,29%,34%,66%
3,240.202,0.24,0.80,0.54,58%,81%,27%
4,240.093,1.00,0.98,1.00,100%,97%,94%

In [20]:
# Atribuo o df de copia ao original
df = df_copia

In [21]:
# Deleto o "df_copia"
del df_copia

In [22]:
df

,Registro_Ensina,Adaptação e Inovação,Capacidade de Execução,Colaboração e Parceria,Comunicação Empática e Mobilizadora,Desenvolvimento Contínuo,Visão Estratégica e Resolução de Problemas
0,240.216,0.02,0.37,0.15,85%,77%,6%
1,240.003,0.85,0.89,0.77,55%,68%,72%
2,240.062,0.23,0.69,0.71,29%,34%,66%
3,240.202,0.24,0.80,0.54,58%,81%,27%
4,240.093,1.00,0.98,1.00,100%,97%,94%
...,...,...,...,...,...,...,...
171,240.038,0.99,0.65,0.92,47%,93%,92%
172,250.055,0.90,0.13,0.53,53%,36%,2%
173,240.102,0.93,0.65,0.98,98%,90%,92%
174,240.132,0.05,0.09,0.09,3%,9%,20%
175,250.152,0.76,0.46,0.96,47%,88%,92%

## Comunicação Empática e Mobilizadora

In [23]:
# Criando uma cópia
df_copia = df.copy()

In [24]:
# Tiramos o símbolo de '%' usando manipulação de string (.str.replace)
# Convertemos o texto que sobrou para número decimal (.astype(float))
# Dividimos por 100 para ficar na escala de 0 a 1 (ex: 85 vira 0.85)

df_copia['Comunicação Empática e Mobilizadora'] = df_copia['Comunicação Empática e Mobilizadora'].str.replace('%', '').astype(float) / 100

In [25]:
df_copia.head()

,Registro_Ensina,Adaptação e Inovação,Capacidade de Execução,Colaboração e Parceria,Comunicação Empática e Mobilizadora,Desenvolvimento Contínuo,Visão Estratégica e Resolução de Problemas
0,240.216,0.02,0.37,0.15,0.85,77%,6%
1,240.003,0.85,0.89,0.77,0.55,68%,72%
2,240.062,0.23,0.69,0.71,0.29,34%,66%
3,240.202,0.24,0.80,0.54,0.58,81%,27%
4,240.093,1.00,0.98,1.00,1.00,97%,94%

In [26]:
# Atribuo o df de copia ao original
df = df_copia

In [27]:
# Deleto o "df_copia"
del df_copia

In [28]:
df

,Registro_Ensina,Adaptação e Inovação,Capacidade de Execução,Colaboração e Parceria,Comunicação Empática e Mobilizadora,Desenvolvimento Contínuo,Visão Estratégica e Resolução de Problemas
0,240.216,0.02,0.37,0.15,0.85,77%,6%
1,240.003,0.85,0.89,0.77,0.55,68%,72%
2,240.062,0.23,0.69,0.71,0.29,34%,66%
3,240.202,0.24,0.80,0.54,0.58,81%,27%
4,240.093,1.00,0.98,1.00,1.00,97%,94%
...,...,...,...,...,...,...,...
171,240.038,0.99,0.65,0.92,0.47,93%,92%
172,250.055,0.90,0.13,0.53,0.53,36%,2%
173,240.102,0.93,0.65,0.98,0.98,90%,92%
174,240.132,0.05,0.09,0.09,0.03,9%,20%
175,250.152,0.76,0.46,0.96,0.47,88%,92%

## Desenvolvimento Contínuo

In [29]:
# Criando uma cópia
df_copia = df.copy()

In [30]:
# Tiramos o símbolo de '%' usando manipulação de string (.str.replace)
# Convertemos o texto que sobrou para número decimal (.astype(float))
# Dividimos por 100 para ficar na escala de 0 a 1 (ex: 85 vira 0.85)

df_copia['Desenvolvimento Contínuo'] = df_copia['Desenvolvimento Contínuo'].str.replace('%', '').astype(float) / 100

In [31]:
df_copia.head()

,Registro_Ensina,Adaptação e Inovação,Capacidade de Execução,Colaboração e Parceria,Comunicação Empática e Mobilizadora,Desenvolvimento Contínuo,Visão Estratégica e Resolução de Problemas
0,240.216,0.02,0.37,0.15,0.85,0.77,6%
1,240.003,0.85,0.89,0.77,0.55,0.68,72%
2,240.062,0.23,0.69,0.71,0.29,0.34,66%
3,240.202,0.24,0.80,0.54,0.58,0.81,27%
4,240.093,1.00,0.98,1.00,1.00,0.97,94%

In [32]:
# Atribuo o df de copia ao original
df = df_copia

In [33]:
# Deleto o "df_copia"
del df_copia

In [34]:
df

,Registro_Ensina,Adaptação e Inovação,Capacidade de Execução,Colaboração e Parceria,Comunicação Empática e Mobilizadora,Desenvolvimento Contínuo,Visão Estratégica e Resolução de Problemas
0,240.216,0.02,0.37,0.15,0.85,0.77,6%
1,240.003,0.85,0.89,0.77,0.55,0.68,72%
2,240.062,0.23,0.69,0.71,0.29,0.34,66%
3,240.202,0.24,0.80,0.54,0.58,0.81,27%
4,240.093,1.00,0.98,1.00,1.00,0.97,94%
...,...,...,...,...,...,...,...
171,240.038,0.99,0.65,0.92,0.47,0.93,92%
172,250.055,0.90,0.13,0.53,0.53,0.36,2%
173,240.102,0.93,0.65,0.98,0.98,0.90,92%
174,240.132,0.05,0.09,0.09,0.03,0.09,20%
175,250.152,0.76,0.46,0.96,0.47,0.88,92%

## Visão Estratégica e Resolução de Problemas

In [35]:
# Criando uma cópia
df_copia = df.copy()

In [36]:
# Tiramos o símbolo de '%' usando manipulação de string (.str.replace)
# Convertemos o texto que sobrou para número decimal (.astype(float))
# Dividimos por 100 para ficar na escala de 0 a 1 (ex: 85 vira 0.85)

df_copia['Visão Estratégica e Resolução de Problemas'] = df_copia['Visão Estratégica e Resolução de Problemas'].str.replace('%', '').astype(float) / 100

In [37]:
df_copia.head()

,Registro_Ensina,Adaptação e Inovação,Capacidade de Execução,Colaboração e Parceria,Comunicação Empática e Mobilizadora,Desenvolvimento Contínuo,Visão Estratégica e Resolução de Problemas
0,240.216,0.02,0.37,0.15,0.85,0.77,0.06
1,240.003,0.85,0.89,0.77,0.55,0.68,0.72
2,240.062,0.23,0.69,0.71,0.29,0.34,0.66
3,240.202,0.24,0.80,0.54,0.58,0.81,0.27
4,240.093,1.00,0.98,1.00,1.00,0.97,0.94

In [38]:
# Atribuo o df de copia ao original
df = df_copia

In [39]:
# Deleto o "df_copia"
del df_copia

In [40]:
df

,Registro_Ensina,Adaptação e Inovação,Capacidade de Execução,Colaboração e Parceria,Comunicação Empática e Mobilizadora,Desenvolvimento Contínuo,Visão Estratégica e Resolução de Problemas
0,240.216,0.02,0.37,0.15,0.85,0.77,0.06
1,240.003,0.85,0.89,0.77,0.55,0.68,0.72
2,240.062,0.23,0.69,0.71,0.29,0.34,0.66
3,240.202,0.24,0.80,0.54,0.58,0.81,0.27
4,240.093,1.00,0.98,1.00,1.00,0.97,0.94
...,...,...,...,...,...,...,...
171,240.038,0.99,0.65,0.92,0.47,0.93,0.92
172,250.055,0.90,0.13,0.53,0.53,0.36,0.02
173,240.102,0.93,0.65,0.98,0.98,0.90,0.92
174,240.132,0.05,0.09,0.09,0.03,0.09,0.20
175,250.152,0.76,0.46,0.96,0.47,0.88,0.92

Gerar arquivo CSV

In [41]:
df.to_csv("Arquivo_Tratado_Autoavaliação", index=False)