In [1]:
import pandas as pd

## LENDO O CSV

In [2]:
df = pd.read_csv('Competências_Avaliação de Terceiros.csv', sep=',')

In [3]:
df.head()

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Desenvolvimento Contínuo_Devolutiva,Desenvolvimento Contínuo_Diálogo,...,Adaptação e Inovação_Revê,Adaptação e Inovação_Planejamento,Capacidade de Execução_Constância,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,2.0,2.0,...,3.0,2.0,3.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,3.0,...,4.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0

Verificando se existe duplicatas

In [4]:
df.duplicated().sum()

np.int64(0)

## Desenvolvimento Contínuo

In [5]:
# Criando uma copia para o df.
df_copia = df
df_copia

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Desenvolvimento Contínuo_Devolutiva,Desenvolvimento Contínuo_Diálogo,...,Adaptação e Inovação_Revê,Adaptação e Inovação_Planejamento,Capacidade de Execução_Constância,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,2.0,2.0,...,3.0,2.0,3.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,3.0,...,4.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,3.0,3.0,...,3.0,3.0,4.0,2.0,2.0,3.0,2.0,3.0,4.0,2.0
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,3.0,3.0,...,3.0,3.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,2.0,...,2.0,3.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,NaN
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,4.0,3.0,...,2.0,2.0,2.0,2.0,2.0,NaN,3.0,2.0,2.0,2.0
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,4.0,2.0,...,3.0,2.0,3.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0

In [6]:
# Primeiro, criamos uma lista com o nome exato das colunas "micro"
cols_desenv_continuo = [
    'Desenvolvimento Contínuo_Devolutiva', 
    'Desenvolvimento Contínuo_Diálogo', 
    'Desenvolvimento Contínuo_Compartilha', 
    'Desenvolvimento Contínuo_Referência'
]

In [7]:
# Criamos a nova coluna "macro".
# O comando .mean(axis=1) tira a média da linha e já dividimos por 4.
df_copia['Desenvolvimento Contínuo'] = df_copia[cols_desenv_continuo].mean(axis=1) / 4

In [8]:
# removemos as colunas "micro" antigas para não poluir a base
df_copia = df_copia.drop(columns=cols_desenv_continuo)

In [9]:
# Atribuo o df de copia ao original
df = df_copia

In [10]:
# Deleto o "df_copia"
del df_copia

In [11]:
df.head()

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Visão Estratégica_Resultados,Visão Estratégica_Ajustar,...,Adaptação e Inovação_Planejamento,Capacidade de Execução_Constância,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0000
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,3.0,2.0,...,2.0,3.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,0.5625
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.6875
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0000

## Visão Estratégica

In [12]:
# Criando uma copia para o df.
df_copia = df
df_copia

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Visão Estratégica_Resultados,Visão Estratégica_Ajustar,...,Adaptação e Inovação_Planejamento,Capacidade de Execução_Constância,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,3.0,2.0,...,2.0,3.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,0.562500
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.687500
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,3.0,2.0,...,3.0,4.0,2.0,2.0,3.0,2.0,3.0,4.0,2.0,0.687500
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,2.0,...,3.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,0.562500
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,2.0,...,3.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,NaN,0.583333
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,2.0,3.0,...,2.0,2.0,2.0,2.0,NaN,3.0,2.0,2.0,2.0,0.875000
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,2.0,2.0,...,2.0,3.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,0.625000

In [13]:
# Primeiro, criamos uma lista com o nome exato das colunas "micro"
cols_visao_estrategica = [
    'Visão Estratégica_Resultados', 
    'Visão Estratégica_Ajustar', 
    'Visão Estratégica_Coerência', 
    'Visão Estratégica_Conectar'
]

In [14]:
# Criamos a nova coluna "macro".
# O comando .mean(axis=1) tira a média da linha e já dividimos por 4.
df_copia['Visão Estratégica'] = df_copia[cols_visao_estrategica].mean(axis=1) / 4

In [15]:
# Removo as colunas "micro" antigas para não poluir a base
df_copia = df_copia.drop(columns=cols_visao_estrategica)

In [16]:
# Atribuo o df de copia ao original
df = df_copia
df

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Colaboração e Parceria_Abertura,Colaboração e Parceria_Engaja,...,Capacidade de Execução_Constância,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo,Visão Estratégica
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,3.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,2.0,2.0,...,3.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,0.562500,0.6250
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,2.0,2.0,...,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.687500,1.0000
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,2.0,3.0,...,4.0,2.0,2.0,3.0,2.0,3.0,4.0,2.0,0.687500,0.6875
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,3.0,4.0,...,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,0.562500,0.6250
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,3.0,...,2.0,2.0,2.0,2.0,1.0,1.0,3.0,NaN,0.583333,0.5625
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,4.0,3.0,...,2.0,2.0,2.0,NaN,3.0,2.0,2.0,2.0,0.875000,0.5625
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,4.0,4.0,...,3.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,0.625000,0.5000

In [17]:
# Deleto o "df_copia"
del df_copia

## Colaboração e Parceria

In [18]:
# Criando uma copia para o df.
df_copia = df
df_copia

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Colaboração e Parceria_Abertura,Colaboração e Parceria_Engaja,...,Capacidade de Execução_Constância,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo,Visão Estratégica
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,3.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,2.0,2.0,...,3.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,0.562500,0.6250
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,2.0,2.0,...,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.687500,1.0000
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,2.0,3.0,...,4.0,2.0,2.0,3.0,2.0,3.0,4.0,2.0,0.687500,0.6875
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,3.0,4.0,...,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,0.562500,0.6250
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,3.0,...,2.0,2.0,2.0,2.0,1.0,1.0,3.0,NaN,0.583333,0.5625
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,4.0,3.0,...,2.0,2.0,2.0,NaN,3.0,2.0,2.0,2.0,0.875000,0.5625
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,4.0,4.0,...,3.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,0.625000,0.5000

In [19]:
# Primeiro, criamos uma lista com o nome exato das colunas "micro"
cols_colabo_parceria = [
    'Colaboração e Parceria_Abertura', 
    'Colaboração e Parceria_Engaja', 
    'Colaboração e Parceria_Ajuda', 
    'Colaboração e Parceria_Parceria'
]

In [20]:
# Criamos a nova coluna "macro".
# O comando .mean(axis=1) tira a média da linha e já dividimos por 4.
df_copia['Colaboração e Parceria'] = df_copia[cols_colabo_parceria].mean(axis=1) / 4

In [21]:
# Removo as colunas "micro" antigas para não poluir a base
df_copia = df_copia.drop(columns=cols_colabo_parceria)

In [22]:
# Atribuo o df de copia ao original
df = df_copia
df

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Adaptação e Inovação_Inovação,Adaptação e Inovação_Metodologia,...,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,0.812500
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,1.0,2.0,...,1.0,2.0,2.0,3.0,2.0,2.0,2.0,0.562500,0.6250,0.500000
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.687500,1.0000,0.625000
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,3.0,2.0,...,2.0,2.0,3.0,2.0,3.0,4.0,2.0,0.687500,0.6875,0.750000
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,3.0,3.0,...,4.0,3.0,3.0,3.0,3.0,3.0,3.0,0.562500,0.6250,0.812500
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,2.0,...,2.0,2.0,2.0,1.0,1.0,3.0,NaN,0.583333,0.5625,0.666667
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,2.0,2.0,...,2.0,2.0,NaN,3.0,2.0,2.0,2.0,0.875000,0.5625,0.833333
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,4.0,4.0,...,2.0,3.0,3.0,1.0,3.0,3.0,2.0,0.625000,0.5000,0.875000

In [23]:
# Deleto o "df_copia"
del df_copia

## Adaptação e Inovação

In [24]:
# Criando uma copia para o df.
df_copia = df
df_copia

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Adaptação e Inovação_Inovação,Adaptação e Inovação_Metodologia,...,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,0.812500
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,1.0,2.0,...,1.0,2.0,2.0,3.0,2.0,2.0,2.0,0.562500,0.6250,0.500000
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,...,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.687500,1.0000,0.625000
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,3.0,2.0,...,2.0,2.0,3.0,2.0,3.0,4.0,2.0,0.687500,0.6875,0.750000
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,3.0,3.0,...,4.0,3.0,3.0,3.0,3.0,3.0,3.0,0.562500,0.6250,0.812500
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,2.0,...,2.0,2.0,2.0,1.0,1.0,3.0,NaN,0.583333,0.5625,0.666667
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,2.0,2.0,...,2.0,2.0,NaN,3.0,2.0,2.0,2.0,0.875000,0.5625,0.833333
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,4.0,4.0,...,2.0,3.0,3.0,1.0,3.0,3.0,2.0,0.625000,0.5000,0.875000

In [25]:
# Crio uma lista com o nome exato das colunas "micro"
cols_adapt_inova = [
    'Adaptação e Inovação_Inovação', 
    'Adaptação e Inovação_Metodologia', 
    'Adaptação e Inovação_Revê', 
    'Adaptação e Inovação_Planejamento'
]

In [26]:
# Crio uma nova coluna "macro".
# O comando .mean(axis=1) tira a média da linha e já dividimos por 4.
df_copia['Adaptação e Inovação'] = df_copia[cols_adapt_inova].mean(axis=1) / 4

In [27]:
# Removo as colunas "micro" antigas para não poluir a base
df_copia = df_copia.drop(columns=cols_adapt_inova)

In [28]:
# Atribuo o df de copia ao original
df = df_copia
df

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Capacidade de Execução_Constância,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,0.812500,1.0000
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,3.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,0.562500,0.6250,0.500000,0.5000
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000,1.0000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.687500,1.0000,0.625000,1.0000
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,4.0,2.0,2.0,3.0,2.0,3.0,4.0,2.0,0.687500,0.6875,0.750000,0.6875
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,0.562500,0.6250,0.812500,0.7500
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,2.0,2.0,2.0,1.0,1.0,3.0,NaN,0.583333,0.5625,0.666667,0.5625
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,2.0,2.0,2.0,NaN,3.0,2.0,2.0,2.0,0.875000,0.5625,0.833333,0.5000
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,3.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,0.625000,0.5000,0.875000,0.8125

In [29]:
# Deleto o "df_copia"
del df_copia

## Capacidade de Execução

In [30]:
# Criando uma copia para o df.
df_copia = df.copy()
df_copia

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Capacidade de Execução_Constância,Capacidade de Execução_Concreta,Capacidade de Execução_Padrões,Capacidade de Execução_Planos,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,0.812500,1.0000
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,3.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,0.562500,0.6250,0.500000,0.5000
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000,1.0000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,0.687500,1.0000,0.625000,1.0000
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,4.0,2.0,2.0,3.0,2.0,3.0,4.0,2.0,0.687500,0.6875,0.750000,0.6875
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,0.562500,0.6250,0.812500,0.7500
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,2.0,2.0,2.0,2.0,1.0,1.0,3.0,NaN,0.583333,0.5625,0.666667,0.5625
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,2.0,2.0,2.0,NaN,3.0,2.0,2.0,2.0,0.875000,0.5625,0.833333,0.5000
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,3.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,0.625000,0.5000,0.875000,0.8125

In [31]:
# Crio uma lista com o nome exato das colunas "micro"
cols_capaci_execucao = [
    'Capacidade de Execução_Constância', 
    'Capacidade de Execução_Concreta', 
    'Capacidade de Execução_Padrões', 
    'Capacidade de Execução_Planos'
]

In [32]:
# Crio uma nova coluna "macro".
# O comando .mean(axis=1) tira a média da linha e já dividimos por 4.
df_copia['Capacidade de Execução'] = df_copia[cols_capaci_execucao].mean(axis=1) / 4

In [33]:
# Removo as colunas "micro" antigas para não poluir a base
df_copia = df_copia.drop(columns=cols_capaci_execucao)

In [34]:
# Atribuo o df de copia ao original
df = df_copia
df.head(1)

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação,Capacidade de Execução
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,4.0,4.0,1.0,1.0,0.8125,1.0,1.0

In [35]:
# Deleto o "df_copia"
del df_copia

## Comunicação Empática

In [36]:
# Criando uma copia para o df.
df_copia = df.copy()
df_copia

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Comunicação Empática_Expectativa,Comunicação Empática_Conflitos,Comunicação Empática_Sensibilidade,Comunicação Empática_Diálogo,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação,Capacidade de Execução
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,4.0,4.0,4.0,4.0,1.000000,1.0000,0.812500,1.0000,1.0000
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,3.0,2.0,2.0,2.0,0.562500,0.6250,0.500000,0.5000,0.5000
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000,1.0000,1.0000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,4.0,4.0,4.0,4.0,0.687500,1.0000,0.625000,1.0000,0.9375
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,4.0,4.0,4.0,4.0,1.000000,1.0000,1.000000,1.0000,1.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,2.0,3.0,4.0,2.0,0.687500,0.6875,0.750000,0.6875,0.6875
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,3.0,3.0,3.0,3.0,0.562500,0.6250,0.812500,0.7500,0.8125
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,1.0,1.0,3.0,NaN,0.583333,0.5625,0.666667,0.5625,0.5000
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,3.0,2.0,2.0,2.0,0.875000,0.5625,0.833333,0.5000,0.5000
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,1.0,3.0,3.0,2.0,0.625000,0.5000,0.875000,0.8125,0.6875

In [37]:
# Crio uma lista com o nome exato das colunas "micro"
cols_comunica_empati= [
    'Comunicação Empática_Expectativa', 
    'Comunicação Empática_Conflitos', 
    'Comunicação Empática_Sensibilidade', 
    'Comunicação Empática_Diálogo'
]

In [38]:
# Crio uma nova coluna "macro".
# O comando .mean(axis=1) tira a média da linha e já dividimos por 4.
df_copia['Comunicação Empática'] = df_copia[cols_comunica_empati].mean(axis=1) / 4

In [39]:
# Removo as colunas "micro" antigas para não poluir a base
df_copia = df_copia.drop(columns=cols_comunica_empati)

In [40]:
# Atribuo o df de copia ao original
df = df_copia
df.head(1)

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação,Capacidade de Execução,Comunicação Empática
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,1.0,1.0,0.8125,1.0,1.0,1.0

In [41]:
# Deleto o "df_copia"
del df_copia

## Arredondando as casas decimais das competencias

In [42]:
df_copia = df.copy()
df_copia

,Registro_Ensina,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação,Capacidade de Execução,Comunicação Empática
0,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,1.000000,1.0000,0.812500,1.0000,1.0000,1.000000
1,240.003,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,2_Consultor(a) pedagógico(a),Escola Municipal Nossa Senhora Rainha dos Anjo...,0.562500,0.6250,0.500000,0.5000,0.5000,0.562500
2,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes,1.000000,1.0000,1.000000,1.0000,1.0000,1.000000
3,240.004,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,1_Consultor(a) pedagógico(a),EMEF Maria José Costa Moraes,0.687500,1.0000,0.625000,1.0000,0.9375,1.000000
4,240.005,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita,1.000000,1.0000,1.000000,1.0000,1.0000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,240.216,2.024,Vitória,Preta,Mulher Cisgênero,Bacharelado,6_Consultor(a) pedagógico(a),EMEF Tancredo de Almeida Neves,0.687500,0.6875,0.750000,0.6875,0.6875,0.687500
332,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,Diretor(a),EMEF Heloísa Abreu Júdice de Mattos,0.562500,0.6250,0.812500,0.7500,0.8125,0.750000
333,250.171,2.025,Vitória,Branca,Homem Cisgênero,Bacharelado,11_Consultor(a) pedagógico(a),EMEF Heloísa Abreu Júdice de Mattos,0.583333,0.5625,0.666667,0.5625,0.5000,0.416667
334,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross,0.875000,0.5625,0.833333,0.5000,0.5000,0.562500
335,240.002,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,10_Consultor(a) pedagógico(a),ETI Irmã Ceciliana Gross,0.625000,0.5000,0.875000,0.8125,0.6875,0.562500

In [43]:
# Agrupando as colunas das competências em uma lista para facilitar
colunas_competencias = [
    'Desenvolvimento Contínuo', 
    'Visão Estratégica', 
    'Colaboração e Parceria', 
    'Adaptação e Inovação', 
    'Capacidade de Execução', 
    'Comunicação Empática'
]

# Aplicando o arredondamento de 2 casas decimais substituindo os valores antigos
df_copia[colunas_competencias] = df_copia[colunas_competencias].round(2)

In [44]:
# Atribuindo "df_copia" a "df"
df = df_copia

In [45]:
# Deleto o "df_copia"
del df_copia

## Fazendo as mudanças na coluna "Registro Ensina"

In [46]:
df_copia = df.copy()

In [47]:
df_copia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336 entries, 0 to 335
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Registro_Ensina           336 non-null    float64
 1   Turma_Ensina              336 non-null    float64
 2   Polo_Ensina               336 non-null    object
 3   Raça_Ensina               336 non-null    object
 4   Gênero_Ensina             336 non-null    object
 5   Grau Acadêmico_Ensina     336 non-null    object
 6   Função_Avaliador(a)       336 non-null    object
 7   Escola_Avaliador          336 non-null    object
 8   Desenvolvimento Contínuo  335 non-null    float64
 9   Visão Estratégica         333 non-null    float64
 10  Colaboração e Parceria    335 non-null    float64
 11  Adaptação e Inovação      335 non-null    float64
 12  Capacidade de Execução    335 non-null    float64
 13  Comunicação Empática      334 non-null    float64
dtypes: float64(8), object(6)
memory usage: 36.9+ KB

In [48]:
# Verificando possível erro

# 1. Quantidade de valores nulos (candidatos sem registro)
nulos = df_copia['Registro_Ensina'].isnull().sum()
print(f"Valores nulos: {nulos}")

# 2. Tipos de dados misturados (ex: texto misturado com número)
tipos = df_copia['Registro_Ensina'].apply(type).value_counts()
print(f"\nTipos de dados encontrados:\n{tipos}")

# 3. Tamanho dos registros (ex: todos deveriam ter 7 caracteres como '240.003')
tamanhos = df_copia['Registro_Ensina'].astype(str).str.len().value_counts()
print(f"\nQuantidade de caracteres por registro:\n{tamanhos}")

# 4. Amostra para inspeção visual (buscando por letras onde só deveria ter números)
amostra = df_copia['Registro_Ensina'].unique()[:15]
print(f"\nAmostra de registros únicos:\n{amostra}")

Valores nulos: 0

Tipos de dados encontrados:
Registro_Ensina
<class 'float'>    336
Name: count, dtype: int64

Quantidade de caracteres por registro:
Registro_Ensina
7    302
6     30
5      4
Name: count, dtype: int64

Amostra de registros únicos:
[240.003 240.004 240.005 240.006 250.006 250.007 240.01  240.013 240.015
 240.016 250.011 250.013 250.017 240.023 240.024]

In [49]:
# Garantindo que todos tenham exatamente 3 casas decimais (restaurando os zeros)
df_copia['Registro_Ensina'] = df_copia['Registro_Ensina'].apply(lambda x: f"{x:.3f}")

In [50]:
df_copia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336 entries, 0 to 335
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Registro_Ensina           336 non-null    object
 1   Turma_Ensina              336 non-null    float64
 2   Polo_Ensina               336 non-null    object
 3   Raça_Ensina               336 non-null    object
 4   Gênero_Ensina             336 non-null    object
 5   Grau Acadêmico_Ensina     336 non-null    object
 6   Função_Avaliador(a)       336 non-null    object
 7   Escola_Avaliador          336 non-null    object
 8   Desenvolvimento Contínuo  335 non-null    float64
 9   Visão Estratégica         333 non-null    float64
 10  Colaboração e Parceria    335 non-null    float64
 11  Adaptação e Inovação      335 non-null    float64
 12  Capacidade de Execução    335 non-null    float64
 13  Comunicação Empática      334 non-null    float64
dtypes: float64(7), object(7)
memory usage: 36.9+ KB

In [51]:
df = df_copia

In [52]:
del df_copia

## Agrupar as notas onde o "Registro Ensina" aparece mais de uma vez.

In [53]:
df_copia = df.copy()

In [54]:
# Separamos as colunas que vão sofrer o cálculo matemático
colunas_competencias = [
    'Desenvolvimento Contínuo', 
    'Visão Estratégica', 
    'Colaboração e Parceria', 
    'Adaptação e Inovação', 
    'Capacidade de Execução', 
    'Comunicação Empática'
]

In [55]:
# Executamos o agrupamento e resetamos o índice
df_copia_agrupado = df_copia.groupby('Registro_Ensina')[colunas_competencias].mean().reset_index()

In [56]:
df_copia_agrupado.head(50)

,Registro_Ensina,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação,Capacidade de Execução,Comunicação Empática
0,240.002,0.750,0.530,0.855,0.655,0.595,0.560
1,240.003,0.780,0.810,0.655,0.750,0.750,0.780
2,240.004,0.845,1.000,0.810,1.000,0.970,1.000
3,240.005,1.000,1.000,1.000,0.970,0.940,1.000
4,240.006,0.715,0.845,0.835,0.905,0.940,0.845
5,240.010,0.620,0.595,0.500,0.470,0.720,0.720
6,240.013,0.595,0.655,0.750,0.690,0.875,0.815
7,240.015,0.970,1.000,1.000,1.000,1.000,1.000
8,240.016,0.665,0.690,0.750,0.625,0.655,0.720
9,240.023,0.750,0.715,0.750,0.780,0.845,0.720
10,240.024,0.940,0.940,0.905,0.940,0.970,0.910
11,240.027,0.805,0.845,0.940,0.685,0.720,0.970
12,240.029,0.970,1.000,0.970,1.000,1.000,0.970
13,240.030,0.780,0.630,0.630,0.690,0.595,0.595
14,240.031,0.845,0.940,0.970,1.000,1.000,1.000
15,240.036,1.000,1.000,1.000,1.000,1.000,1.000
16,240.038,0.940,0.810,0.900,0.780,0.815,0.970
17,240.039,0.460,0.470,0.460,0.560,0.530,0.595
18,240.046,0.530,0.560,0.645,0.530,0.720,0.625
19,240.054,0.780,0.845,0.750,0.875,0.780,0.750
20,240.055,0.655,0.810,0.815,0.845,0.720,0.780
21,240.059,0.780,0.810,0.845,0.780,0.685,0.780
22,240.060,0.375,0.290,0.415,0.315,0.375,0.335
23,240.061,0.690,0.690,0.805,0.690,0.565,0.685
24,240.062,0.310,0.620,0.380,0.595,0.810,0.560
25,240.066,0.970,1.000,0.905,0.970,1.000,1.000
26,240.071,0.885,0.875,0.960,0.905,0.900,0.845
27,240.072,1.000,1.000,0.970,1.000,1.000,1.000
28,240.073,0.905,1.000,0.875,0.940,0.970,1.000
29,240.075,0.555,0.655,0.780,0.715,0.720,0.750
30,240.076,0.815,0.750,0.740,0.845,0.780,0.845
31,240.080,1.000,1.000,1.000,1.000,1.000,1.000
32,240.081,1.000,1.000,0.970,0.875,1.000,0.970
33,240.084,0.750,0.780,0.810,0.715,0.750,0.750
34,240.085,0.845,0.970,0.810,0.905,1.000,0.970
35,240.087,0.720,0.845,0.655,0.880,0.685,0.905
36,240.090,0.910,0.970,0.910,0.655,0.905,1.000
37,240.091,0.655,0.655,0.655,0.780,0.715,0.685
38,240.092,0.910,0.845,0.880,0.655,0.815,0.780
39,240.093,0.540,0.530,0.520,0.410,0.380,0.625
40,240.097,0.750,0.750,0.880,0.690,0.910,0.785
41,240.099,0.875,0.875,0.750,1.000,0.810,0.810
42,240.101,0.815,0.845,0.785,0.845,0.790,0.865
43,240.102,0.815,0.810,0.875,0.845,0.910,0.815
44,240.103,0.810,0.940,0.780,0.780,0.845,0.750
45,240.104,0.970,0.970,0.960,1.000,0.970,0.970
46,240.105,0.970,1.000,0.940,1.000,1.000,0.845
47,240.106,0.835,0.905,0.960,0.845,0.845,0.905
48,240.108,0.790,0.845,1.000,0.940,0.875,0.940
49,240.109,0.905,0.970,0.910,0.970,1.000,0.940

In [57]:
# Arredondamos as notas
df_copia_agrupado = df_copia_agrupado.round(2)

In [58]:
df_agrupado = df_copia_agrupado
df_agrupado

,Registro_Ensina,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação,Capacidade de Execução,Comunicação Empática
0,240.002,0.75,0.53,0.86,0.66,0.60,0.56
1,240.003,0.78,0.81,0.66,0.75,0.75,0.78
2,240.004,0.84,1.00,0.81,1.00,0.97,1.00
3,240.005,1.00,1.00,1.00,0.97,0.94,1.00
4,240.006,0.72,0.84,0.84,0.90,0.94,0.84
...,...,...,...,...,...,...,...
163,250.165,0.75,0.69,0.94,0.78,0.68,0.78
164,250.166,0.43,0.38,0.47,0.38,0.44,0.28
165,250.167,0.94,0.94,0.97,1.00,0.84,0.76
166,250.171,0.57,0.59,0.74,0.66,0.66,0.58
167,250.178,0.97,0.81,0.97,0.81,0.78,0.90

In [59]:
del df_copia_agrupado

## UTILIZANDO O MERGE NA TABELA PARA RESGATAR AS COLUNAS NA TABELA

In [60]:
df_copia = df.copy()

In [61]:
# Definimos quais colunas de texto (dados do candidato) queremos resgatar
colunas_contexto = [
    'Registro_Ensina', 
    'Turma_Ensina', 
    'Polo_Ensina', 
    'Raça_Ensina', 
    'Gênero_Ensina', 
    'Grau Acadêmico_Ensina',
    'Função_Avaliador(a)',
    'Escola_Avaliador'
]

In [62]:
# Vamos na base original e pegamos apenas essas colunas, removendo as duplicatas. 
# Assim, teremos apenas 1 linha com os dados cadastrais para cada Registro.
df_cadastro = df_copia[colunas_contexto].drop_duplicates(subset='Registro_Ensina')

In [63]:
# Fazemos o "Procv" (Merge) juntando as Notas Médias com os Dados Cadastrais
df_copia_final = pd.merge(df_agrupado, df_cadastro, on='Registro_Ensina', how='left')

In [64]:
df_copia_final.head()

,Registro_Ensina,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação,Capacidade de Execução,Comunicação Empática,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador
0,240.002,0.75,0.53,0.86,0.66,0.60,0.56,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross
1,240.003,0.78,0.81,0.66,0.75,0.75,0.78,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...
2,240.004,0.84,1.00,0.81,1.00,0.97,1.00,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes
3,240.005,1.00,1.00,1.00,0.97,0.94,1.00,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita
4,240.006,0.72,0.84,0.84,0.90,0.94,0.84,2.024,Caruaru,Parda,Homem Cisgênero,Licenciatura,Diretor(a),ETI Irmã Ceciliana Gross

In [65]:
df = df_copia_final

In [66]:
del df_copia_final

In [67]:
df.head()

,Registro_Ensina,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação,Capacidade de Execução,Comunicação Empática,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina,Função_Avaliador(a),Escola_Avaliador
0,240.002,0.75,0.53,0.86,0.66,0.60,0.56,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),ETI Irmã Ceciliana Gross
1,240.003,0.78,0.81,0.66,0.75,0.75,0.78,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado,Diretor(a),Escola Municipal Nossa Senhora Rainha dos Anjo...
2,240.004,0.84,1.00,0.81,1.00,0.97,1.00,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura,Coordenador(a) Pedagógico(a),EMEF Maria José Costa Moraes
3,240.005,1.00,1.00,1.00,0.97,0.94,1.00,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado,Coordenador(a) Pedagógico(a),EE José de Mesquita
4,240.006,0.72,0.84,0.84,0.90,0.94,0.84,2.024,Caruaru,Parda,Homem Cisgênero,Licenciatura,Diretor(a),ETI Irmã Ceciliana Gross

## Apagando as duas colunas que não serão usadas "Função_Avaliador(a)" e "Escola_Avaliador"

In [68]:
df_copia = df.copy()

In [69]:
# Removendo as colunas de contexto do avaliador que perderam o sentido após a média
df_copia = df_copia.drop(columns=['Função_Avaliador(a)', 'Escola_Avaliador'])

In [70]:
df = df_copia

In [71]:
del df_copia

In [72]:
df.head()

,Registro_Ensina,Desenvolvimento Contínuo,Visão Estratégica,Colaboração e Parceria,Adaptação e Inovação,Capacidade de Execução,Comunicação Empática,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina
0,240.002,0.75,0.53,0.86,0.66,0.60,0.56,2.024,Caruaru,Branca,Mulher Cisgênero,Licenciatura
1,240.003,0.78,0.81,0.66,0.75,0.75,0.78,2.024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado
2,240.004,0.84,1.00,0.81,1.00,0.97,1.00,2.024,Vitória,Sem Informação,Homem Cisgênero,Licenciatura
3,240.005,1.00,1.00,1.00,0.97,0.94,1.00,2.024,Cuiabá,Preta,Homem Cisgênero,Bacharelado
4,240.006,0.72,0.84,0.84,0.90,0.94,0.84,2.024,Caruaru,Parda,Homem Cisgênero,Licenciatura

## Utilizando o Merge para unir as tabelas

In [103]:
df_auto = pd.read_csv('Arquivo_Tratado_Autoavaliação')
df_terceiros = pd.read_csv('Arquivo_Tratado_Avaliação_Terceiros')

In [104]:
# Fazendo o cruzamento perfeito (mantendo apenas quem está nas duas bases) e adicionando sufixos
df_final = pd.merge(
    df_auto, 
    df_terceiros, 
    on='Registro_Ensina', 
    how='inner', 
    suffixes=('_Auto', '_Terc')
)

In [105]:
# Transformando o float (2.024) no texto real de categoria ('2024')
df_final['Turma_Ensina'] = (df_final['Turma_Ensina'] * 1000).astype(int).astype(str)

# Arredondando APENAS as colunas de métricas e gaps, protegendo a nossa Turma!
colunas_para_arredondar = [col for col in df_final.columns if '_Auto' in col or '_Terc' in col]
df_final[colunas_para_arredondar] = df_final[colunas_para_arredondar].round(2)

In [106]:
df_final.head()

,Registro_Ensina,Adaptação e Inovação_Auto,Capacidade de Execução_Auto,Colaboração e Parceria_Auto,Comunicação Empática_Auto,Desenvolvimento Contínuo_Auto,Visão Estratégica_Auto,Desenvolvimento Contínuo_Terc,Visão Estratégica_Terc,Colaboração e Parceria_Terc,Adaptação e Inovação_Terc,Capacidade de Execução_Terc,Comunicação Empática_Terc,Turma_Ensina,Polo_Ensina,Raça_Ensina,Gênero_Ensina,Grau Acadêmico_Ensina
0,240.216,0.02,0.37,0.15,0.85,0.77,0.06,0.84,0.84,0.72,0.84,0.84,0.84,2024,Vitória,Preta,Mulher Cisgênero,Bacharelado
1,240.003,0.85,0.89,0.77,0.55,0.68,0.72,0.78,0.81,0.66,0.75,0.75,0.78,2024,Petrolina,Preta,Não Binária ou Não Binário,Bacharelado
2,240.062,0.23,0.69,0.71,0.29,0.34,0.66,0.31,0.62,0.38,0.60,0.81,0.56,2024,Vitória,Branca,Não Binária ou Não Binário,Bacharelado
3,240.202,0.24,0.80,0.54,0.58,0.81,0.27,0.97,1.00,0.75,1.00,1.00,1.00,2024,Vitória,Preta,Mulher Cisgênero,Bacharelado e Licenciatura
4,240.093,1.00,0.98,1.00,1.00,0.97,0.94,0.54,0.53,0.52,0.41,0.38,0.62,2024,Vitória,Branca,Homem Cisgênero,Licenciatura

## Verificando as outras colunas

In [88]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Registro_Ensina                157 non-null    float64
 1   Adaptação e Inovação_Auto      157 non-null    float64
 2   Capacidade de Execução_Auto    157 non-null    float64
 3   Colaboração e Parceria_Auto    157 non-null    float64
 4   Comunicação Empática_Auto      157 non-null    float64
 5   Desenvolvimento Contínuo_Auto  157 non-null    float64
 6   Visão Estratégica_Auto         157 non-null    float64
 7   Desenvolvimento Contínuo_Terc  157 non-null    float64
 8   Visão Estratégica_Terc         157 non-null    float64
 9   Colaboração e Parceria_Terc    157 non-null    float64
 10  Adaptação e Inovação_Terc      157 non-null    float64
 11  Capacidade de Execução_Terc    157 non-null    float64
 12  Comunicação Empática_Terc      157 non-null    float64
 13  Turma_Ensina                   157 non-null    object
 14  Polo_Ensina                    157 non-null    object
 15  Raça_Ensina                    157 non-null    object
 16  Gênero_Ensina                  157 non-null    object
 17  Grau Acadêmico_Ensina          157 non-null    object
 18  Gap_Desenvolvimento Contínuo   157 non-null    float64
 19  Gap_Visão Estratégica          157 non-null    float64
 20  Gap_Colaboração e Parceria     157 non-null    float64
 21  Gap_Adaptação e Inovação       157 non-null    float64
 22  Gap_Capacidade de Execução     157 non-null    float64
 23  Gap_Comunicação Empática       157 non-null    float64
dtypes: float64(19), object(5)
memory usage: 29.6+ KB

Turma_Ensina

In [86]:
df_final[['Turma_Ensina']]

    Turma_Ensina
0           2024
1           2024
2           2024
3           2024
4           2024
..           ...
152         2024
153         2025
154         2024
155         2024
156         2025

[157 rows x 1 columns]

Polo_Ensina

In [94]:
df_final['Polo_Ensina'].unique()

array(['Vitória', 'Petrolina', 'Caruaru', 'Campo Grande', 'São Luís',
       'Luziânia', 'Cuiabá', 'Águas Lindas de Goiás'], dtype=object)

Raça_Ensina

In [95]:
df_final['Raça_Ensina'].unique()

array(['Preta', 'Branca', 'Parda', 'Sem Informação', 'Amarela',
       'Prefiro não informar'], dtype=object)

Gênero_Ensina

In [96]:
df_final['Gênero_Ensina'].unique()

array(['Mulher Cisgênero', 'Não Binária ou Não Binário',
       'Homem Cisgênero', 'Mulher Transsexual', 'Prefiro não informar'],
      dtype=object)

Grau Acadêmico_Ensina

In [109]:
df_final['Grau Acadêmico_Ensina'].unique()

array(['Bacharelado', 'Bacharelado e Licenciatura', 'Licenciatura',
       'Sem Informação', 'Tecnólogo'], dtype=object)

In [108]:
df_final['Grau Acadêmico_Ensina'] = df_final['Grau Acadêmico_Ensina'].replace('Tecnólogo (CST)', 'Tecnólogo')

## SALVAR O CSV COM AS MUDANÇAS NA TABELA DE "AVALIAÇÃO DE TERCEIROS"

In [79]:
# NÃO SALVAR MAIS NADA NESSE !!!
df.to_csv("Arquivo_Tratado_Avaliação_Terceiros", index=False)

## EXPORTANDO O ARQUIVO CSV FINAL

In [112]:
df_final.to_csv('Base_Dashboard.csv', index=False)